FROM node:16

# Create app directory
WORKDIR /usr/src/app


# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN yarn ci --only=production \
    yarn sequelize:database1:drop \
    yarn sequelize:database1:create \
    yarn sequelize:database1:migrate \
    yarn sequelize:database1:seed:all \
    yarn build
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 5000
CMD [ "node", "dist/server.js" ]